site/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gallery.urls', namespace='gallery'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site/gallery/urls.py
from django.conf.urls import url
from . import views as gallery_views

urlpatterns = [
    url(r'^$', gallery_views.home, name='home'),

    url(r'^albums/$', gallery_views.albums, name='albums'),
    # url(r'^album/$', gallery_views.albums, name='albums'),
    url(r'^album/(?P<id>\d+)/$', gallery_views.photos, name='photos'),
]

site/gallery/models.py
from django.db import models
from versatileimagefield.fields import VersatileImageField, PPOIField

from os import path
from uuid import uuid4


def upload_photos(instance, filename):
    f, ext = path.splitext(filename)
    name = '%s%s' %(uuid4().hex, ext)
    return 'gallery/{i}'.format(i=name)


class Season(models.Model):
    title = models.CharField(max_length=30)
    rate = models.PositiveIntegerField(default=0)
    published = models.BooleanField(default=True)
    # date = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сезон'
        verbose_name_plural = 'Сезони'
        ordering = ['-rate']


class Album(models.Model):
    title = models.CharField(max_length=50)
    date = models.DateField(auto_now=False, auto_now_add=True)
    season = models.ForeignKey('Season', related_name='albums', on_delete=models.CASCADE)
    published = models.BooleanField(default=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = 'Альбом'
        verbose_name_plural = 'Альбоми'
        ordering = ['date']


class Photo(models.Model):
    image = VersatileImageField(upload_to=upload_photos, ppoi_field='ppoi', null=True, blank=True)
    ppoi = PPOIField(default='0.5x0.5')
    album = models.ForeignKey('Album', related_name='photos', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Фотографія'
        verbose_name_plural = 'Фотографії'
        # ordering = ['pk']

    def show_title(self):
        img = str(self.image).split('/')[-1]
        title = img.split('.')[0]
        return str(title)

    def show_previw_image(self):
        if self.image:
            return u'<img src="%s" width="100" />' %(self.image.url)
        return 'Image not found'
    show_previw_image.short_description = 'Превю'
    show_previw_image.allow_tags = True

    def save(self, *args, **kwargs):
        # do something
        qs = super(Photo, self).save(*args, **kwargs)
        if self.image == None or self.image == '':
            self.delete()
        return qs

site/gallery/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponse
from .models import *

# Create your views here.

def home(request):
    seasons = Season.objects.filter(published=True)
    context = {
        'seasons': seasons
    }
    return render_to_response('gallery/index.html', context)


def albums(request):
    seasons = Season.objects.filter(published=True)
    context = {
        'title': 'Альбоми',
        'seasons': seasons,
    }
    return render_to_response('gallery/albums.html', context)


def photos(request, id):
    albums = Album.objects.filter(published=True).exclude(id=id).order_by('?')[:4]
    album = get_object_or_404(Album, id=id)
    context = {
        'title': 'Фотографії',
        'album': album,
        'albums': albums,
    }
    return render_to_response('gallery/photos.html', context)

site/gallery/templates/new_change_form.html
{% extends "admin/change_form.html" %}

{% block after_field_sets %}
<link href="http://hayageek.github.io/jQuery-Upload-File/4.0.10/uploadfile.css" rel="stylesheet">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="http://hayageek.github.io/jQuery-Upload-File/4.0.10/jquery.uploadfile.min.js"></script>

<div id="previewupload">
    Upload
</div>

<script>
    $(document).ready(function() {
        $( "#id_album" ).change(function() {
            var id = $('#id_album option:selected').val();

            if(id != '') {
                $("#previewupload").show();

                $("#previewupload").uploadFile({
                    url:".",
                    fileName:"images",
                    multiple:true,
                    acceptFiles:"image/*",
                    sequential:true,
                    sequentialCount:1,
                    maxFileSize:3500*1024,  // about 3 MB
                    showPreview:true,
                    previewHeight: "100px",
                    previewWidth: "100px",
                    formData: {
                        "csrfmiddlewaretoken": "{{ csrf_token }}",
                        "album": id
                    }
                });
            }
            else {
                $("#previewupload").hide();
            }

        });

    });
</script>

{{ block.super }}
{% endblock %}

site/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Галарейка{% endblock %}</title>

    <link rel="stylesheet" href="{% static  'libs/bootstrap3/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static  'libs/bootstrap3/css/bootstrap-theme.min.css' %}">

    <link rel="stylesheet" href="{% static  'libs/slider-pro/css/slider-pro.min.css' %}">

    <link rel="stylesheet" href="{% static  'assets/css/style.css' %}">
</head>
<body>

    <div id="preloader" class="preloader">
        <div class="loader"></div>
    </div>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="{% static 'libs/jquery.min.js' %}"></script>
    <script src="{% static 'libs/bootstrap3/js/bootstrap.min.js' %}"></script>

    <script src="{%  static 'libs/slider-pro/js/jquery.sliderPro.min.js' %}"></script>

    <script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>

site/templates/gallery/albums.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1>Albums</h1>

    {% for season in seasons %}
        <h1>{{ season.title }}</h1>
        <div class="row">
        {% if season.albums.all %}
            {% for album in season.albums.all %}
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        {% with album.photos.all|first as photo %}
                        <a href="{% url 'gallery:photos' album.id %}">
                            <img src="{{ MEDIA_URL }}{{ photo.image.crop.350x350 }}" alt="no photo">
                        </a>
                        {% endwith %}
                        <div class="caption alert-info">
                            <h3>{{ album.title }}</h3>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
        <div class="alert alert-warning" role="alert">
            Вибачте но для цього сезону, альбомів не існує.
        </div>
        {% endif %}
        </div>
    <hr>
    {% endfor %}


{% endblock %}

site/templates/gallery/index.html
{% extends 'base.html' %}

{% block title %} {% endblock %}

{% block content %}
    <h1>Seasons</h1>

    <select class="" name="">
        {% for season in seasons %}
            <option value="">{{ season.title }}</option>
        {% endfor %}
    </select>

    <div class="row">
        <a href="{% url 'gallery:albums' %}">Альбоми</a>
    </div>
{% endblock %}

site/templates/gallery/photos.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1>Альбом: {{ album.title|upper }}</h1>

    <div id="slider-pro" class="slider-pro">
        <div class="sp-slides">
            {% for photo in album.photos.all %}
            <div class="sp-slide">
                <img src="{{ MEDIA_URL }}{{ photo.image.url }}" class="img-responsive" alt="no photo"
                     data-src="{{ MEDIA_URL }}{{ photo.image.url }}"/>
            </div>
            {% endfor %}
            <!-- <div class="sp-slide">
                <img class="sp-image" src="../src/css/images/blank.gif"
                    data-src="http://bqworks.com/slider-pro/images/image3_medium.jpg"
                    data-small="http://bqworks.com/slider-pro/images/image3_small.jpg"
                    data-medium="http://bqworks.com/slider-pro/images/image3_medium.jpg"
                    data-large="http://bqworks.com/slider-pro/images/image3_large.jpg"
                    data-retina="http://bqworks.com/slider-pro/images/image3_large.jpg"/>
            </div> -->
        </div>

        <div class="sp-thumbnails">
            {% for photo in album.photos.all %}
                <div class="sp-thumbnail">
                    <img src="{{ MEDIA_URL }}{{ photo.image.thumbnail.100x100 }}" class="img-responsive" alt="no photo">
                </div>
            {% endfor %}
            <!-- <img class="sp-thumbnail" src="http://bqworks.com/slider-pro/images/image1_thumbnail.jpg"/>
            <img class="sp-thumbnail" src="http://bqworks.com/slider-pro/images/image2_thumbnail.jpg"/>
            <img class="sp-thumbnail" src="http://bqworks.com/slider-pro/images/image3_thumbnail.jpg"/> -->
        </div>
    </div>

    <hr><br>
    <div class="row">
        {% for album in albums %}
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    {% with album.photos.all|first as photo %}
                    <a href="{% url 'gallery:photos' album.id %}">
                        <img src="{{ MEDIA_URL }}{{ photo.image.crop.350x350 }}" alt="no photo">
                    </a>
                    {% endwith %}
                    <div class="caption alert-info">
                        <h3>{{ album.title }}</h3>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="col-xs-12">
        <a href="{% url 'gallery:albums' %}">Повернутись до альбомів...</a>
    </div>
    <br><br>

{% endblock %}